### ISSUE TITLE
Feature Request-New Blueprint for Climate Mode

### ISSUE THREAD

**Issue by ckhyatt** [TheFes/ha-blueprints#1]
In my quest to replace the Amazon Echo devices I am recreating all the functionality we now use. Your local weather and MA blueprints have been critical in replacing that functionality. Thanks! 

Voice control of our thermostats is a frequently used feature. Get temperature works, there's a PR in for Set temperature that looks like it will appear in Core soon. I have created custom sentences to change mode. "Set upstairs to Heat". I have a solution for everything except querying mode. With the Echo I ask "What's upstairs set to?" It will reply with the mode and temperature. "The heat's set to 68." I can't figure out a way to do this in a custom sentence. I would be happy to pay you to create a blueprint-or whatever is the best solution-for this. 

Thanks for your excellent work!

**Comment by TheFes** [comment]
Personally I would create a custom sentence for this (so not a trigger based automation). There are no actions to be performed, you're just asking it about the current state and temperature.

You could even overrule the surrent GetTemperature intent, and add sentences like `what's the <name> set to` and change the response so it includes the mode

Something like this

### intent

```yaml
language: "en"
intents:
  HassClimateGetTemperature:
    data:
      # Get temperature of a climate in the same area as a satellite device
      - sentences:
          - "<what_is> [the] [current] <temp> [<here>]"
          - "how (hot|cold|warm|cool) is it [<here>]"
          - "<what_is> the climate [control] set to [<here>]"
        requires_context:
          area:
            slot: true

      # Get temperature of a climate in an area or with a name
      - sentences:
          - "<what_is> [the] [current] <temp> [of] <name>"
          - "<what_is> [the] [current] <temp> <in> <area>"
          - "<what_is> <area> [current] <temp>"
          - "<what_is> <name> [current] <temp>"
          - "how (hot|cold|warm|cool) is (<name>|[it <in>] <area>)"
          - "<what_is> <name> set to"
```

### response
```yaml
language: en
responses:
  intents:
    HassClimateGetTemperature:
      default: >
        {% set temperature = state_attr(state.entity_id, 'current_temperature') %}
        {% if temperature == 1: %}
        It's currently on {{ state.state }} and set to {{ temperature }} degree
        {% else: %}
        It's currently on {{ state.state }} and set to {{ temperature }} degrees
        {% endif %}
```
