### ISSUE TITLE
Triggering these automations without voice?

### ISSUE THREAD

**Issue by JamesMcNaught** [TheFes/ha-blueprints#50]
These automations are super useful, but is there a simple way to trigger them without a voice prompt?
I’d like an automatic weather and calendar announcement each morning, when I trigger my roller blinds to open.

**Comment by TheFes** [comment]
You can use the `conversation.process` action. It will give an action response which you can use in the announcement

```yaml
action: conversation.process
data:
  text: "What's on the agenda for tomorrow"
  agent_id: conversation.chatgpt
response_variable: calander_response
```

This will result in something like this
```yaml
response:
  speech:
    plain:
      speech: |-
        Tomorrow, 22 June, you have the following on the agenda:
        
        - BBQ with neighbors from 15:00 to 16:00
      extra_data: null
  card: {}
  language: nl
  response_type: action_done
  data:
    targets: []
    success: []
    failed: []
conversation_id: 01JY9RQJ3TF5ZYK365EG3Y18Z3
continue_conversation: false
```
